name: weather-bridge
services:
  weather-bridge:
    image: weatherbridge:testing
    container_name: weatherbridge
    ports:
        - "8080:8080"
    environment:
      - OP_CONNECT_HOST=http://connect-api:8080
      - TZ=America/Phoenix
    labels:
      - diun.enable=false
    restart: unless-stopped
