name: Docker Build from Dockerfile

on:
  push:
    tags:
      - '**'

jobs:

  build_and_push_docker_image:

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: billbinaz/weatherbridge
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=WeatherBridge
            org.opencontainers.image.description=Connection software for automation
            org.opencontainers.image.version=${{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}          
