name: Docker Build from Dockerfile

on:
  push:
    tags:
      - '**'

  pull_request:
    branches: [ "master" ]

jobs:

  build_and_push_docker_image:

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mandatory to use the extract version from tag action

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      - name: Display version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=$(echo "${{ steps.get_version.outputs.version }}")
          echo $VERSION

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: billbinaz/weatherbridge
          tags: |
            value=latest, enable=startsWith(github.ref, 'refs/tags/v')
            value= $MAJOR.$MINOR.$PATCH, enable=startsWith(github.ref, 'refs/tags/v')
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}          
